---
# tasks file for systems
- name: create systems users
  user:
    name: "{{ item.key }}"
    state: "{{ item.value.state | default(None) }}"
    uid: "{{ item.value.uid     | default(0) }}"
    shell: "{{ item.value.shell | default(None) }}"
    home: "{{ item.value.home | default(None) }}"

  loop: "{{ systems.users|dict2items }}"



- name: install common system packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ systems.packages }}"

- name: install ntp
  yum:
    name: ntp
    state: present
