---
- name: app servers play
  hosts: app
  become: true
  vars:
    fav:
      fruit: mango
      car: skoda
  roles:
  - { role: apache, tags: www }
  - { role: php, tags: ['www','php'] }
  - { role: frontend, tags: devopsdemo }
  
  tags:
    - frontend

