- name: Clean website 
  hosts: lbsrv
  become: true
  tasks:
    - name: adding nginx repository
      yum_repository:
        name: nginx
        description: Nginx repo
        
        baseurl: https://nginx.org/packages/centos/$releasever/$basearch/
        gpgcheck: no
        state: absent

    - name: Install nginx
      package:

        name: "{{ item }}"
        state: absent
      loop:
        - nginx
        - git

    - name: remove directory
      file:
        path: /usr/share/nginx/html/app
        state: absent