---
- import_playbook: db.yml

- name: application deoployment
  hosts: app
  serial: 1
  become: true
  max_fail_percentage: 40
  
  vars:
    app:
      version: 1.6

  pre_tasks:
    - name: disable app server from haproxy
      haproxy:
        state: disabled
        host: '{{ inventory_hostname }}'
      delegate_to: lbsrv
  roles:
    - apache

 


  post_tasks:

    - name: wait for app serrvers to be available
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 80
        state: started
        timeout: 3000
      delegate_to: local
    

    - name: enable to the haproxy
      haproxy:
        state: enabled
        host: '{{ inventory_hostname }}'
      delegate_to: lbsrv
      
  