- name: register variable example
  hosts: local
  tasks:
    - name: run a shell command and register
      shell: "/sbin/ip addr show wlan0"
      register: result

    - name: showing registered
      debug:
        var: result

    - name: execute this task conditionally
      command: uptime
      when: result.changed != true