- name: base system configuration for linux servers

  hosts: prod
  become: true
  tasks:
    - name: Add admin user
      user: 
        name: admin
        comment: 'Admin User'
        uid: 5001
        state: present
      
    - name: remove user dojo if it is present
      user:
        name: dojo
        state: absent

    - name: Install tree package
      package:
        name: tree
        state: present

    - name: install ntp package
      yum:
        name: ntp
        state: latest
    - name: Start service ntp, if not started
      service:
        name: ntpd
        state: started


- name: configure app servers
  hosts: app
  become: true
  tasks:
    - name: create a user deploy
      user:
        name: deploy
        state: present



    - name: install git package 
      package: 
        name: git
        state: latest
