- name: Deploy a Static HTML Site
  hosts: lbsrv
  become: true
  tasks:
    - name: adding nginx repository
      yum_repository:
        name: nginx
        description: Nginx repo
        
        baseurl: https://nginx.org/packages/centos/$releasever/$basearch/
        gpgcheck: no

    - name: Install nginx
      package:

        name: "{{ item }}"
        state: installed
      loop:
        - nginx
        - git

    - name: deploy the application
      git:
        repo: https://github.com/schoolofdevops/html-sample-app.git
        dest: /usr/share/nginx/html/app    

    - name: run nginx
      service:
        name: nginx
        state: restarted
        enabled: yes