- name: create /opt/app/release
  file:
    path: /opt/app/release
    recurse: yes
    owner: "{{ apache.user }}"
    group: "{{ apache.group }}"
    state: directory
    mode: '0755'


- name: unzip release version {{ app.version }} of the app
  unarchive:
    src: https://github.com/dkr290/devops-demo-app/archive/{{ app.version }}.zip
    dest: /opt/app/release
    owner: "{{ apache.user }}"
    group: "{{ apache.group }}"
    creates: /opt/app/release/devops-demo-app-{{ app.version }}
    remote_src: yes


- name: create symlink to /var/www
  file:
    src: /opt/app/release/devops-demo-app-{{ app.version }}
    dest: /var/www/html/app
    owner: "{{ apache.user }}"
    group: "{{ apache.group }}"
    state: link

- name: copy application config 
  template:
    src: config.ini.j2
    dest: /var/www/html/app/config.ini
    owner: "{{ apache.user }}"
    group: "{{ apache.group }}"
    mode: 0744


